language: c
sudo: false
os: linux
dist: bionic

notifications:
  email: false

addons:
  apt:
    packages:
      - libgettextpo-dev
      - libcrack2-dev
      - libpcre3-dev
      - libperl-dev
      - libssl-dev
      - clang-8
      - gcc-8

compiler:
  - clang-8
  - gcc-8

env:
  - OPTIONAL_CONF_ARGS=""
  - OPTIONAL_CONF_ARGS="--with-perl"
  - OPTIONAL_CONF_ARGS="--enable-contrib"

script:
  - ./configure --enable-nls --enable-ssl --with-cracklib ${OPTIONAL_CONF_ARGS}
  - make -j $(nproc)

matrix:
  allow_failures:
    - env: OPTIONAL_CONF_ARGS="--enable-contrib"
